name: maildir-utils
base: core20
version: 1.12.11
summary: Maildir indexer/searcher with an Emacs UI
description: |
  mu is a tool for dealing with e-mail messages stored in the
  Maildir-format, on Unix-like systems. mu’s main purpose is to help you to
  find the messages you need, quickly; in addition, it allows you to view
  messages, extract attachments, create new maildirs and more.

  Features:
  * fast indexing for Maildir, Maildir+ and Maildir-on-VFAT
  * search for messages based on the sender, receiver, subject, date-range,
    size, priority, words in message, flags (signed, encrypted, new,
    replied, has-attachment,…), message-id, maildir, tags, attachment
    (name, mime-type, text) and more
  * support for encrypted and signed messages
  * command-line tools for indexing, searching, viewing, adding/removing
    messages, extracting attachments, exporting/searching address lists,
    creating maildirs
  * accent/case normalization - so angstrom matches Ångström
  * can be integrated with other e-mail clients such as mutt and
    Wanderlust.
  * mu4e, an emacs-based e-mail client based on mu

confinement: strict
grade: stable

apps:
  mu:
    command: bin/mu
    command-chain:
      - setup-env
    plugs:
      - home
      - gpg-keys # for gpg key access
      - network-bind # for gpg-agent
      - desktop # for various pinentry frontends
      - x11
      - wayland
      - password-manager-service # for pinentry-gnome3

parts:
  mu:
    plugin: meson
    source: https://github.com/djcb/mu
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/
    build-packages:
      - libglib2.0-dev
      - libjson-glib-dev
      - libgmime-3.0-dev
      - libxapian-dev
      - texinfo
    build-snaps:
      - emacs
    stage-packages:
      - libassuan0
      - libgmime-3.0-0
      - libgpgme11
      - libxapian30
      - libjson-glib-1.0-0
      - gpg
      - gpg-agent
      - gpgconf
      - gpgsm
      - gpgv
      - pinentry-gnome3
      - rsync
    build-environment:
      - CFLAGS: "$CFLAGS -O2"
    override-pull: |
      snapcraftctl pull
  command-chain:
    source: .
    plugin: dump
    stage:
      - setup-env
# found with gpgconf --list-dirs
layout:
  /etc/gnupg:
    bind: $SNAP/etc/gnupg
  /usr/bin/dirmngr:
    bind-file: $SNAP/usr/bin/dirmngr
  /usr/bin/gpg:
    bind-file: $SNAP/usr/bin/gpg
  /usr/bin/gpg-agent:
    bind-file: $SNAP/usr/bin/gpg-agent
  /usr/bin/gpg-connect-agent:
    bind-file: $SNAP/usr/bin/gpg-connect-agent
  /usr/bin/gpgconf:
    bind-file: $SNAP/usr/bin/gpgconf
  /usr/bin/gpgsm:
    bind-file: $SNAP/usr/bin/gpgsm
  /usr/bin/gpgv:
    bind-file: $SNAP/usr/bin/gpgv
  /usr/bin/pinentry:
    bind-file: $SNAP/usr/bin/pinentry-gnome3
  /usr/lib/gnupg:
    bind: $SNAP/usr/lib/gnupg
  /usr/share/gnupg:
    bind: $SNAP/usr/share/gnupg
